apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sublime-api-ingress
spec:
  rules:
  - host: api.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-api-service
            port:
              number: 80