apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    labels:
        app: postgres
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:latest
                  ports:
                      - containerPort: 5432
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "256m"
                      limits:
                          memory: "512Mi"
                          cpu: "512m"
                  env:
                      - name: POSTGRES_DB
                        valueFrom:
                            secretKeyRef:
                                name: db-credentials
                                key: DB_NAME
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: db-credentials
                                key: DB_USER
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: db-credentials
                                key: DB_PASS
---
apiVersion: v1
kind: Service
metadata:
    name: postgres
spec:
    selector:
        app: postgres
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
