# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: sqlite-pv
# spec:
#   storageClassName: local-path
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/host_mnt/c/Users/olman/k3d-volumes/sqlite"