# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sqlite-pvc
# spec:
#   storageClassName: local-path
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
